name: Split providers into their individual repos

on:
  push:
    branches:
      - master

jobs:
  split:
    name: Split Providers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
     # Required due to GH detached head bug https://github.com/actions/checkout/issues/6
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        run: composer install -vvv

      - name: Split
        run: ./vendor/bin/monorepo-builder split --max-processes 8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
