name: Close Subtree PRs

on:
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
jobs:
  close:
    name: Close Subtree PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Required due to GH detached head bug https://github.com/actions/checkout/issues/6
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"

      - name: Set up PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.4'
          coverage: none

      - name: Composer Install
        run: composer install -vvv

      - name: Close PRs
        run: ./tools/close-subtree-prs.php
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
